version: "3.8"

services:
  uno_server:
    build:
      context: /home/ubuntu/uno/backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: always
    container_name: uno_server
    networks:
      - docker_shared_network
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./site:/site
      - /home/ubuntu/uno/frontend/dist:/site/uno/
      - /home/ubuntu/blog/dist:/site/blog/
      - /home/ubuntu/secret-pastebin/frontend/dist:/site/sneak/
      - /home/ubuntu/nginx-config/nginx-logs:/var/log/nginx
    networks:
      - docker_shared_network


  rss_reader:
    image: ghcr.io/0x2e/fusion:latest
    container_name: rss_reader
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PASSWORD=fusion
      - DB=/data/fusion.db
    restart: "unless-stopped"
    volumes:
      - /home/ubuntu/rss_data/:/fusion/data
    networks:
      - docker_shared_network

networks:
  docker_shared_network:
    driver: bridge
