version: '3.8'

services:
  uno_server:
    build:
      context: /home/ubuntu/uno/backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: always
    container_name: uno_server
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./site:/site
      - /home/ubuntu/uno/frontend/dist:/site/uno/
      - /home/ubuntu/blog/dist:/site/blog/

