version: '3.8'

services:
 web:
    build: .
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./site:/site
      - /home/ubuntu/uno/frontend/dist:/site/uno/
      - /home/ubuntu/blog/dist:/site/blog/

